[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/sitemap.xml"
[headers.values]
Content-Type = "text/xml; charset=utf-8"
