[[redirects]]
    from = "/*"
    to = "/"
    status = 200

[[redirects]]
    from = "/*"
    to = "/404.html"
    status = 404

# Sitemap
[[headers]]
    for = "/sitemapindex.xml"
    [headers.values]
        X-Jim = "WORKS"
        Content-Type = "text/xml; charset=utf-8"

[[headers]]
    for = "/sitemap-static.xml"
    [headers.values]
        X-Jim = "WORKS"
        Content-Type = "text/xml; charset=utf-8"