[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Sitemap
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
  Content-Type = "application/xml"
  Content-Encoding = "UTF-8"
  Custom-Header = "10"