#[[redirects]]
#    from = "/*"
#    to = "/index.html"
#    status = 200

# Sitemap
[[headers]]
    for = "/sitemapindex.xml"
    [headers.values]
        X-Jim = "WORKS"
        Content-Type = "text/xml; charset=utf-8"

[[headers]]
    for = "/sitemap-static.xml"
    [headers.values]
        X-Jim = "WORKS"
        Content-Type = "text/xml; charset=utf-8"

[[plugins]]
    package = "gatsby-plugin-netlify"