export enum IMAGES_KEYS_TYPE {
  PEOPLE = 'PEOPLE',
  FAMOUS = 'FAMOUS',
  BUILDING = 'BUILDING',
  CHILDREN = 'CHILDREN',
  KULTURE = 'KULTURE',
  SPORT = 'SPORT',
  ZAHID = 'ZAHID',
  SALINA = 'SALINA',
  TEACHER = 'TEACHER',
  PRIEST = 'PRIEST',
  MONK = 'MONK',
  CHURCH = 'CHURCH',
  MONASTERY = 'MONASTERY',
  VASILIAN = 'VASILIAN',
  UGKC = 'UGKC',
}

export enum YEARS_KEYS_TYPE {
  Y1905_1939 = '1905-1939',
  Y1939_1945 = '1939-1945',
  Y1945_1989 = '1945-1989',
  Y1989_2000 = '1989-2000',
  Y2000_PRESENT = '2000-*',
}

export const IMAGES_KEYS = {
  [IMAGES_KEYS_TYPE.PEOPLE]: 'люди',
  [IMAGES_KEYS_TYPE.FAMOUS]: 'відомий',
  [IMAGES_KEYS_TYPE.BUILDING]: 'будинки',
  [IMAGES_KEYS_TYPE.CHILDREN]: 'діти',
  [IMAGES_KEYS_TYPE.KULTURE]: 'культура',
  [IMAGES_KEYS_TYPE.SPORT]: 'спорт',
  [IMAGES_KEYS_TYPE.ZAHID]: 'захід',
  [IMAGES_KEYS_TYPE.SALINA]: 'Саліна',
  [IMAGES_KEYS_TYPE.TEACHER]: 'вчитель',
  [IMAGES_KEYS_TYPE.PRIEST]: 'священник',
  [IMAGES_KEYS_TYPE.MONK]: 'монах',
  [IMAGES_KEYS_TYPE.CHURCH]: 'церква',
  [IMAGES_KEYS_TYPE.MONASTERY]: 'монастир',
  [IMAGES_KEYS_TYPE.VASILIAN]: 'Василіяни',
  [IMAGES_KEYS_TYPE.UGKC]: 'УГКЦ'
}

export const STATIC_FOLDER_PATH = '/static/photos'
